### ISSUE TITLE
Image Quality Control Network

### ISSUE THREAD

**Issue by Ludwig-Graef** [mkirchler/transferGWAS#1]
Dear all,
I am working on causal inference and would like to use your features as they seem quite promising. 

As you mentioned, the images vary in quality. I would like to sort out the low quality images. 
Unfortunately, I cannot use the eids that you provide (as far as I know, UK Biobank mixes the eids for very institution). 

Is it possible to get the image classification model and model weights? 

Thanks in advance!

Best regards
L

**Comment by mkirchler** [comment]
Hi, yeah, you're right, the IIDs are not transferable across UKB applications, we noticed that only after releasing them. For the QC we trained a network on this data: https://github.com/HzFu/EyeQ
It'd probably be easiest if you just re-train your own CNN on that data set, we didn't do any special tricks there but I'd have to search for the original model. Since we did some manual visual QC after filtering with this model, the step will not be fully reproducible anyway, unfortunately.
If you really need our model, I can look into retrieving it from an older server next week, though :)
