### ISSUE TITLE
Some questions about images and genotypes

### ISSUE THREAD

**Issue by lyangfan** [mkirchler/transferGWAS#5]
Hi：
I have read your article. Your work is not only innovative but also meaningful. I am currently conducting research on human fundus images and have some questions to ask you.

**Comment by lyangfan** [comment]
I downloaded images with IDs 21015 (left eye) and 21016 (right eye) from UKB. I have some uncertainties about the naming of each image. For example, for individual **1030816**, there are two images in the left eye: **1030816_21015_0_0.png** and **1030816_21015_1_0.png**. For individual **1031077**, there are **1031077_21015_0_0.png** and **1031077_21015_0_1.png**. In the names of these two individuals' images, "_1" appears in different positions. Do you know what each position represents? When conducting GWAS analysis, which image did you specifically use?

**Comment by lyangfan** [comment]
In the appendix of your article, it is mentioned that "Imputed genotype data was filtered according to minor allele frequency (MAF ≥ 0.1%), Hardy-Weinberg equilibrium (significance level: 10−12), imputation quality (information score ≥ 0.4), as well as SNP and sample missingness of maximal 10%." However, in the ```preprocessing_imp.sh``` script, I only see MAF and Hardy-Weinberg equilibrium. Could you please explain how you proceeded with the latter two filtering criteria?

**Comment by mkirchler** [comment]
Hi, thanks for your interest!
Regarding the image filenames: the last `_0`, `_1` etc denote the first or second image taken in direct succession. We did some manual and automated QC filtering here, but it might be sufficient to just use the last one. Since publishing the paper, there have been some other works for better QC of retinal fundus images, I think, maybe check them out if it's a big issue. The first `_1_`, `_0_` etc should denote the visit, if I remember correctly. Unfortunately, the IIDs are randomized between applications, so I can't share the images we have used.
The imputation quality scoring was done at the end before plotting & reporting results - we still ran the GWAS for all SNPs. The SNP & indiv missingness was done using BOLT, as specified here: https://github.com/mkirchler/transferGWAS/blob/8382d4389f02ed904693ee28a694d18f0e611626/lmm/run_lmm.py#L80-L81

**Comment by lyangfan** [comment]
> Hi, thanks for your interest! Regarding the image filenames: the last `_0`, `_1` etc denote the first or second image taken in direct succession. We did some manual and automated QC filtering here, but it might be sufficient to just use the last one. Since publishing the paper, there have been some other works for better QC of retinal fundus images, I think, maybe check them out if it's a big issue. The first `_1_`, `_0_` etc should denote the visit, if I remember correctly. Unfortunately, the IIDs are randomized between applications, so I can't share the images we have used. The imputation quality scoring was done at the end before plotting & reporting results - we still ran the GWAS for all SNPs. The SNP & indiv missingness was done using BOLT, as specified here:
> 
> https://github.com/mkirchler/transferGWAS/blob/8382d4389f02ed904693ee28a694d18f0e611626/lmm/run_lmm.py#L80-L81
Thank you for your patience! Thank you very much
